### ISSUE TITLE
[Enhancement] Use crypto.randomBytes() over loop-based generation

### ISSUE THREAD

**Issue by jupjohn** [NotNotQuinn/twitch-chat-colorchanger#2]
In the implementation of the `randomHex()` function a set of known hexadecimal characters is looped over and each char is picked using a random integer. To streamline this method, a call to `crypto.randomBytes(byteCount)` should be used in conjunction with a `byte[]#toString('hex')` call.

**Comment by NotNotQuinn** [comment]
Anyone can do this if they want
